### ISSUE TITLE
Back and forward page not showing

### ISSUE THREAD

**Issue by meowmeowxw** [turing753/minimal-functional-fox#1]
Hi, your theme is great, however the forward and back button don't display correctly.

![firefox-bug-theme](https://user-images.githubusercontent.com/43200867/70899525-b1917980-1fee-11ea-9a92-845fe8f996d6.png)

What should I change to make them visible?

**Comment by mut-ex** [comment]
Did you copy the entire contents of the repository to your chrome folder? Seems like you are missing the forward and back button SVG files.

**Comment by meowmeowxw** [comment]
I forgot them, thanks (sorry for the stupid issue)

**Comment by mut-ex** [comment]
No worries. Glad to help.
