### ISSUE TITLE
Weird space beneath tab bar

### ISSUE THREAD

**Issue by rojnwa** [turing753/minimal-functional-fox#11]
After updating the theme I'm getting some weird 'bar' beneath my tabs. My desktop resolution is 1366x768 in case that helps you in any way.

![pic-full-200109-1253-41](https://user-images.githubusercontent.com/19150352/72065760-3ebeaa00-32df-11ea-8f1b-e29b6665fd71.png)

**Comment by schwopo** [comment]
I am having the same issue at 1080p

**Comment by Ghoul2077** [comment]
Try editing userChrome.css and put --tabs-container-height: 100px;
This will probably fix it up

**Comment by rojnwa** [comment]
> Try editing userChrome.css and put --tabs-container-height: 100px;
> This will probably fix it up

This worked (actually I'm preferring 90 instead of 100). Still kinda confused why it's so big in the first place.

**Comment by mut-ex** [comment]
> > Try editing userChrome.css and put --tabs-container-height: 100px;
> > This will probably fix it up
> 
> This worked (actually I'm preferring 90 instead of 100). Still kinda confused why it's so big in the first place.

I chose the values based on what made everything look best on my setup (I have a 2560x1440 display). The screenshot in the README shows what it looks like for me with the current userChrome. It isn't one size fits all and you should feel free to tweak things to your liking :)
