### ISSUE TITLE
A bad  result ?

### ISSUE THREAD

**Issue by manujose94** [turing753/minimal-functional-fox#13]
I have tried to implement this theme in my firefox v71 (Ubuntu 19.19) but I think that the result does not resemble what it should be.
![Screenshot-20200109211059-1543x906](https://user-images.githubusercontent.com/6168971/72101297-afd48080-3324-11ea-9096-0c7e0eb73b37.png)

**Comment by mut-ex** [comment]
The latest commit is for Firefox 72. You can either upgrade or try this version: https://github.com/turing753/minimal-functional-fox/tree/b44440d9dd9f7052b5dfbefc072e1262c365061c

**Comment by manujose94** [comment]
I have used that version and now it looks great. Thank you.

**Comment by mut-ex** [comment]
Glad to help!
