### ISSUE TITLE
How to display scrollbar?

### ISSUE THREAD

**Issue by lakkiy** [turing753/minimal-functional-fox#17]
I want to show scrollbar but didn't find config about it.

**Comment by ianmajkut** [comment]
did you find help? because I have the same problem and I need help

**Comment by mut-ex** [comment]
Remove the relevant portion in the userContent.css file.

**Comment by ianmajkut** [comment]
where is it supposed to be? because I couldn't find it

**Comment by mut-ex** [comment]
Did you install using the script or manually? Check out the 'Manual Install' section in the README to find your user directory. You will find the userContent.css file in the chrome directory.

**Comment by ianmajkut** [comment]
Yes, yes. What i meant is where is the scrollbar section in the file because i look for them and it doesn't appear

**Comment by mut-ex** [comment]
![Screenshot_20201111-121059_GitHub-01.jpeg](https://user-images.githubusercontent.com/21265981/98854161-6f97d000-2417-11eb-8f0d-9f35ce921933.jpeg)

**Comment by ianmajkut** [comment]
Thanks!
