### ISSUE TITLE
Visualize multi-selected tabs

### ISSUE THREAD

**Issue by mknw** [turing753/minimal-functional-fox#21]
What's the issue about:
Tabs multiselection is enabled by default in firefox quantum. One can use the feature by holding CTRL and clicking the wanted tabs. 

Expected behaviour:
selected tabs are marked
What happens instead:
they aren't (but they're still selected)

I added this in userChrome.css, l. 186:
```
.tabbrowser-tab[multiselected="true"] {⏎
    background-color: none !important;⏎
    background-image: linear-gradient(to left, #1f4037, #99f2c8) !important;⏎
    color: black !important;⏎
    font-weight: var(--tab-font-weight) !important;⏎
}
```
which can perhaps be a starting point.
Thanks for your work!

**Comment by mut-ex** [comment]
Thank you for pointing out this issue. I will include the fix for it along with rest of fixes for FF 75.

**Comment by mut-ex** [comment]
Please try out the latest version :) Does it work ok for you now?

**Comment by mknw** [comment]
Multi tab selection does work now, thank you! 

Extra info:
however, the default size is too big for my tastes.  So I'm reverting back to a previous version of yours that I modified until I'll have time to re-tweek the newer one.
To be completely honest, I'd shrink everything even more than [this](https://github.com/mknw/minimal-functional-fox/blob/master/userChrome.css) (Ctrl+F "changed"), but then things start overflowing here and there. 

Just typing all this here in case you'll consider different sizings in next versions. (that'd be awesome!)
I really like the cleaner, sharp corners version though. Especially as far as spacing and pinned tabs are involved.

**Comment by mut-ex** [comment]
Apologies for the late reply.  I used pts instead of px for the font size so that they would scale according to the resolution. In retrospect I should have done the same for all the other sizes and spaces. Thank you for the suggestion and I think it shouldn't be too hard to do that. If not I can definitely add a "compact" version.
