### ISSUE TITLE
FF 75 issues

### ISSUE THREAD

**Issue by abridgedcarp** [turing753/minimal-functional-fox#22]
Just updated to FF75 on Manjaro Linux and it's now having some weird graphics issues with the tab container where the top of the tab container looks a bit chopped off

**Comment by mut-ex** [comment]
Thanks for pointing out. I am working on re-writing most of the CSS, expect an update soon!

**Comment by abridgedcarp** [comment]
Sounds great! Thank you much!

**Comment by mut-ex** [comment]
Uploaded the new config file. Check it out and let me know if it fixes your issues.

**Comment by abridgedcarp** [comment]
Wow, it looks even better now than it ever did before. Thanks much!
