### ISSUE TITLE
No search result icons

### ISSUE THREAD

**Issue by saloniamatteo** [turing753/minimal-functional-fox#24]
Hello! I would like to know how to add search result icons. Here's a screenshot:

![ff](https://user-images.githubusercontent.com/28765699/81209774-3ea29280-8fd1-11ea-84d4-18f0c838161d.png)
Also, is there any way to add the "X" button to the tabs?
![tabs](https://user-images.githubusercontent.com/28765699/81209924-6c87d700-8fd1-11ea-8b80-9c65713e7c45.png)

I'm running Firefox 76 (64 bit) on Arch Linux (kernel 5.6.10-arch1-1)

**Comment by mut-ex** [comment]
Sorry for the late reply.

Both of those things are an aspect of the theme :)  That said you can get the search result favicons by removing the following rule from the userChrome.css

`.urlbarView-favicon, .urlbarView-type-icon {
  display: none !important;
}`

You can get the close button back by removing the following selector:

`.tab-close-button {
 display: none !important;
}`

**Comment by saloniamatteo** [comment]
Thanks!!!
