### ISSUE TITLE
Arrows in bookmarks menu are huge and taking up whole screen

### ISSUE THREAD

**Issue by xydian** [turing753/minimal-functional-fox#3]
Hi, 

first of all, thank you for your great work. Your custom theme looks amazing.

i do have a small issue. The arrows in the bookmark menu (show all bookmarks) are taking up the whole screen when i activate your theme. 

This is how it looks normally: 
![screenshot_old_bookmarks](https://user-images.githubusercontent.com/15960032/70956503-7174da00-2074-11ea-9536-a5cf45d5976c.png)

This is how it looks when your userChrome.css is in my profiles
![screenshot_new_bookmarks](https://user-images.githubusercontent.com/15960032/70956502-7174da00-2074-11ea-8ce0-ccee31d921a4.png)

Do you have an idea on how to fix it? Thank you very much in advance

**Comment by mut-ex** [comment]
I am glad you like it. And thank you for pointing out that issue! It was due to the arrow *.svg assets being too large. I resized them to match Firefox's expected size.

You can simply replace your local *.svg files with the updated ones from the repository. That should fix your issue.

**Comment by xydian** [comment]
Yes its working now, thank you very much :)
