### ISSUE TITLE
 No mozilla user directory found.

### ISSUE THREAD

**Issue by vorticalbox** [turing753/minimal-functional-fox#31]
the script is failing to find my profile folder but if manually type in the find it finds the folder

```
sh -c "$(curl -fsSL https://raw.githubusercontent.com/mut-ex/minimal-functional-fox/master/install.sh)"
sh: 50: [[: not found
 [!!] No mozilla user directory found. Terminating...
```

```
find ~/.mozilla/firefox -maxdepth 1 -type d -regextype egrep -regex '.*[a-zA-Z0-9]+.default-release' 

/home/vorticalbox/.mozilla/firefox/usjhv61h.default-release

```

**Comment by jcads** [comment]
I also had this issue. I fixed it by creating my own `install.sh` file then copied the repo's `install.sh` codes.

**Comment by Bjorn99** [comment]
Well, I am using debian. So, my firefox default directory's name is **".default-esr"** and not **".default-release"**.So, I edited the **"default-release**" line inside **"install.sh"** script file by using an editor and changed it to **"default.esr"**. It worked!

**Comment by pngdeity** [comment]
This seems like anticipated behavior as indicated by the inclusion in the README of the advice to "inspect the install script for projects you aren't familiar with."

**Comment by vorticalbox** [comment]
> This seems like anticipated behavior as indicated by the inclusion in the README of the advice to "inspect the install script for projects you aren't familiar with."

as in my example, I ran the command in my terminal from the install.sh https://github.com/mut-ex/minimal-functional-fox/blob/master/install.sh#L48 and it correctly finds the folder when ran directly but not from within the script
