### ISSUE TITLE
Incorrect font in url bar

### ISSUE THREAD

**Issue by katkauma** [turing753/minimal-functional-fox#33]
Hello,
There is a different font in the url bar than is shown in the gif example - I've included a screenshot.  I think the problem is somewhere on my end (not having the correct font, possibly) but I would appreciate guidance in fixing the problem!  
Thank you.
![Screenshot from 2020-11-11 14-44-55](https://user-images.githubusercontent.com/43046498/98857043-7e3cb200-242c-11eb-8e60-f7e1414590f9.png)

**Comment by mut-ex** [comment]
Hi, the default fonts are mononoki and Cantarell.
