### ISSUE TITLE
gmail tickmarks not showing

### ISSUE THREAD

**Issue by mknw** [turing753/minimal-functional-fox#5]
Thank you for your amazing work.
Selection tick boxes for different emails on gmail.com disappear when applying this theme.
Let me know if I can help.

**Comment by mut-ex** [comment]
Thank you first of all!

To clarify are you referring to these tick marks?

![2019-12-17-120406_371x299_scrot](https://user-images.githubusercontent.com/21265981/71022128-639b7500-20c5-11ea-8618-a147b3e060a0.png)
