### ISSUE TITLE
No location .mozilla/firefox/<my-profile-name>/chrome/

### ISSUE THREAD

**Issue by GrbavaCigla** [turing753/minimal-functional-fox#6]
I use archlinux, and I can't find the location.

**Comment by xydian** [comment]
I use arch too, it is within your home directory and you have to create the chrome folder.

Edir: and the folder is not called "my-profile-name", you have to insert your profile name

**Comment by GrbavaCigla** [comment]
Yes, know I have to insert my name there.
So location will be: ~/.mozilla/firefox/chrome ?

**Comment by xydian** [comment]
No, within .mozilla/firefox there is one (or multiple) profile folders. In my case it is named 0q967ui3.default-release. Dont know if it will be the same on your machine. Within this folder you create a new folder chrome. And within this folder you must place userChrome.css and the other files of this repo

**Comment by GrbavaCigla** [comment]
Ok thanks!
Also, I should read documentation next time: https://wiki.archlinux.org/index.php/Firefox/Tweaks#General_user_interface_CSS_settings

**Comment by UchihaSR** [comment]
greetings, i was stuck at this issue i created a chrome folder and pasted all the files. but i dont see any chnages in firefox.
![mozilla_config](https://user-images.githubusercontent.com/52357560/72205541-57c78680-34aa-11ea-80ea-23bf869ff435.png)

**Comment by mut-ex** [comment]
Did you enable user stylesheets in the settings as per the README?

**Comment by UchihaSR** [comment]
yes, i did as as per the readme. this is where i am failing.
