### ISSUE TITLE
Theme is broken after firefox 72.0 update

### ISSUE THREAD

**Issue by eromatiya** [turing753/minimal-functional-fox#8]
Hey, I just want to report that the theme is not working properly after updating to:  
`Mozilla Firefox 72.0`

![20200107_145050](https://user-images.githubusercontent.com/40349590/71874568-36d6fc80-315d-11ea-9677-ca5dfd281c6b.png)

**Comment by pradyungn** [comment]
I can concur this

**Comment by mut-ex** [comment]
Thanks for reporting! I am almost done fixing the theme and will push the changes within the next 24 hours.

**Comment by mut-ex** [comment]
I have pushed the fixed userChrome. If you encounter any bugs please feel free top open another issue.
