### ISSUE TITLE
No X button for the tabs

### ISSUE THREAD

**Issue by ghost** [turing753/minimal-functional-fox#9]
My X button is gone for my tabs.
![image](https://user-images.githubusercontent.com/46574798/71999541-e84f5e00-3241-11ea-8e84-d415fc15ca5b.png)

**Comment by blairryan** [comment]
Comment out line 155 in userChrome.css.

`.tab-close-button,`

**Comment by mut-ex** [comment]
The close button being removed is part of the theme. But you can follow @blairryan 's suggestion to get it back. However the close button might look squished.
